FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o asc-phone-numbers-service

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/go-service .
EXPOSE 8080
CMD ["./go-service"]